# Generated by Django 6.0.6 on 2026-06-25 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('announcement_text', models.TextField(blank=True, null=True)),
                ('announcement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=50)),
                ('regulated_area_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('supply_category', models.CharField(max_length=50)),
                ('housing_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('sale_price_krw', models.BigIntegerField(blank=True, null=True)),
                ('deposit_krw', models.BigIntegerField(blank=True, null=True)),
                ('area_text', models.CharField(max_length=100)),
                ('exclusive_area_sqm', models.FloatField(blank=True, null=True)),
                ('supply_household_count', models.IntegerField(blank=True, null=True)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('special_supply_types_available', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('input_snapshot', models.JSONField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
