version: '3.8'

services:
  # 1. Django 백엔드 서비스 (도커 허브 이미지 사용)
  django-backend:
    image: dongyoon99/django-backend:latest
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - django-db:/app/data  # SQLite db 보존용 볼륨
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_DB_PATH=/app/data/db.sqlite3
      - FASTAPI_API_URL=http://fastapi-backend:8080
    env_file:
      - .env
    depends_on:
      - fastapi-backend

  # 2. FastAPI 백엔드 서비스 (도커 허브 이미지 사용)
  fastapi-backend:
    image: dongyoon99/fastapi-backend:latest
    container_name: fastapi-backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  # 3. React 프론트엔드 서비스 (도커 허브 이미지 사용)
  frontend:
    image: dongyoon99/frontend-react:latest
    container_name: frontend-react
    ports:
      - "3000:80"  # 브라우저에서 http://localhost:3000 으로 접속
    depends_on:
      - django-backend
      - fastapi-backend

volumes:
  django-db:
