server {
    listen 80;
    server_name localhost;
    client_max_body_size 20M; # 최대 업로드 용량을 20MB로 설정


    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API 요청을 django-backend 컨테이너로 프록시
    location /api/ {
        proxy_pass http://django-backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
